### ISSUE TITLE
[feature]: Navigation for the Reading Tab

### ISSUE THREAD

**Issue by ghost** [quran/quran.com-frontend-next#1274]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

Suppose a user is reading the page 42 in the Raeding Tab and then he decided to continue reading onwards in the Translation tab.
Then he will have to scroll 42 pages to go to the top and change the tab (tabs can only be switch from the top).

So i will request to remove the current navigation button (to navigate 'NEXT PAGE' and 'PREVIOUS PAGE') and instead of it give a button to quickly go to the top.
Because this button will be more useful to the user.

Also for just navigating 'Next page' and 'Previous page' , there is no need to give a button. Doing it manually is a better experience.

### Your purposed solution for this feature

Instead of the current Navigation button, provide a button to quickly go to the top like 
![IMG_20220218_144423](https://user-images.githubusercontent.com/99866687/154665109-428da18f-174e-4b1f-8757-60ebc90f61e3.jpg)

**Comment by osamasayed** [comment]
Jazak Allah Khairan for you suggestion, I get your point but we find the navigation up and buttons to be more useful to the users and been used quite a lot since we released it. We are planning to include the Translation/Reading View switcher in the context menu so the user doesn't have to scroll up to change the current view.
