### ISSUE TITLE
[feature]: Redirect to previous.quran.com when browsing from a low-end device

### ISSUE THREAD

**Issue by amarlab7** [quran/quran.com-frontend-next#1785]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

present site doesn't load in some previous browsers. #1536 

### Your purposed solution for this feature

if it is anyhow possible to redirect automatically to previous.quran.com when visiting the site from old browsers

**Comment by osamasayed** [comment]
Alsalamu Alikum @amarlab7, we are using [CSS Logical Properties and Values](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) and since some old browsers don't support them, we redirect to previous.quran.com already. Our detection logic might not be 100% accurate though so feel free to open a PR and we can discuss it inshAllah.

**Comment by hazem3500** [comment]
Following https://github.com/quran/quran.com-frontend-next/issues/1630#issuecomment-1437330001

I'm guessing since all modern browsers now support CSS Logical properties, we could remove the code that redirects to previous.quran.com 🤷 

Or at least close this issue 👀
