### ISSUE TITLE
[bug]: Two Recitations At The Same Time

### ISSUE THREAD

**Issue by M-Arnone** [quran/quran.com-frontend-next#1908]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

[macOS Monterey]
Two Recitations At The Same Time.
I play one recitation and so far that's ok. But, when I play a second (for example I made a mistake and I want to choose another surah), the two recitations are playing together instead of the second one replace the first one. And again, when I click the button "pause" the second stop but the first continue to play.

https://user-images.githubusercontent.com/56111638/215194704-e4d60ac3-bd40-40ed-95c1-9a33d48329cd.mov

### Steps to reproduce

1. Play one recitation.
2. Play a second recitation.
3. Click the button pause to listen only first recitation chosen.

### Environment (please complete the following information) and Add any other context about this bug

OS : macOS Monterey
Browser : //
Version : 1.20.2

### Environment

Production(quran.com)

**Comment by hazem3500** [comment]
Are you sure this issue is for the Quran.com web application? 🤔 

From the video you've shown, it looks like the [ios App](https://apps.apple.com/us/app/quran-by-quran-com-qran/id1118663303), not the web application 😅 

Maybe post this issue in [the ios repo](https://github.com/quran/quran-ios)? 👀 

I did try to reproduce it on my Macbook but couldn't reproduce it 😅. Everytime I press the back button, it auto-closes the recitation 🤷

**Comment by hazem3500** [comment]
Here's a video trying to reproduce it 👇 

[Kapture 2023-02-04 at 18.36.36.webm](https://user-images.githubusercontent.com/22430645/216778919-1d09ea91-51d6-464c-a309-2906915ba0b1.webm)


P.S: [Kap](https://getkap.co/) is a great screen recorder 😉, pair it with [Background Music](https://github.com/kyleneideck/BackgroundMusic#recording-system-audio) to record computer audio 👌

**Comment by M-Arnone** [comment]
Yes it's on the ios app, wrong repo sorry. 
But for me, the bug is still there. I've just tried now. 
I'm on macOS monterey (12.5) with M1 chip and the version of the app is still 1.20.2.
