### ISSUE TITLE
[bug]: Font size decreases while reading

### ISSUE THREAD

**Issue by h4mmad** [quran/quran.com-frontend-next#1952]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

The font size decreases in Surah Taha, from ayah 13

![image](https://user-images.githubusercontent.com/55020862/233873230-905c9acc-2b48-4cdd-95a7-aa47c9d9f465.png)

### Steps to reproduce

While reading Surah Taha, I noticed a decrease in font size

### Environment (please complete the following information) and Add any other context about this bug

OS: Ubuntu
Browser: Chrome

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
Alsalamu Alikum, Jazak Allah Khairan for reporting. I don't think this is a bug. The smaller font is a fallback font until the main font (King Fahad Complex V1) finishes loading. If the text size does not update to normal (should happen pretty quickly), it means it failed to load the main font due to a connection issue. Just to confirm is it a persisting issue?
