### ISSUE TITLE
[bug]: Arabic not showing when language is changed

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#1960]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When switching between languages, the Arabic text disappears. Issue originally reported [here](https://feedback.quran.com/bugs/p/arabic-not-showing-when-change-language).

### Steps to reproduce

1. Open [Ayatul Kursi](https://quran.com/ayatul-kursi) from Incognito
2. Switch to Bengali
3. Switch back to English
4. Switch to Bengali again
5. You will notice the Arabic text no longer appears.

![Apr-28-2023 07-34-27](https://user-images.githubusercontent.com/15169499/235055587-8e5ecd70-ef4c-4b3d-9fcf-8790caedd76b.gif)

### Environment (please complete the following information) and Add any other context about this bug

OS: MacOs Monetery 12.6.4
Browser: Chrome
Version: 112.0.5615.137

### Environment

Production(quran.com)

**Comment by ThatSameer** [comment]
I can reproduce the bug on the production site but not locally. Anyone else not been able to reproduce locally?

OS: MacOS Ventura 13.1
Tried it on Chrome 112.0.5615.137 and Firefox 112.0.1 both in incognito

**Comment by talal-najam** [comment]
Salam. I looked at this today. I can reproduce it locally on chrome without incognito mode. I suspect it happens when I switch to Urdu, Indonesian, or Bangali locales. The quranFont in redux changes from `text_indopak` to `code_v1` (I assume as a fallback font?) in regular chrome, which triggers `useQcfFont` hook. In incognito mode, firefox, or Edge, the text remains as text_indopak for those locales and that hook doesn't get triggered.

**Comment by talal-najam** [comment]
Salam. I can reproduce it locally on regular chrome on Windows (works fine in incognito surprisingly). It happens when I switch to Urdu, Indonesian, or Bangali locales a.k.a. text_indopak. 

Upon selecting the language, `quranFont` in redux changes from `text_indopak` to `code_v1` which triggers `useQcfFont` hook. In incognito mode, firefox, or Edge, the text remains as text_indopak for those locales and that hook doesn't get triggered.  

The font change from text_indopak to code_v1 seems to be happening because of persist/REHYDRATE redux action.

**Comment by afilahkle** [comment]
it seems the Arabic is showing with certain languages while not other, i mean when it disappear it doesn't disappear for ever if you changed it to a language in which it appear, it will show up again.

**Comment by talal-najam** [comment]
quick workaround / hack is to select the language again, which brings back the Arabic text.

Upon investigation, I think I found some issues switching between multiple translations (locally and on prod):
1- Sometimes the Arabic text isn't switched properly or just disappears
2- Sometimes translation text is not accurate from what's selected
3- Redux-persist sometimes has issues updating quranFont in local storage

I think this may be a bigger task to look at this translation and locale piece.
