### ISSUE TITLE
Advanced Copy Problem

### ISSUE THREAD

**Issue by selim** [quran/quran.com-frontend-next#753]
If you advanced copy an ayah,  next advanced copy confuses selection, every time shows same ayah. I first copied 2:32 after I want to copy 2:37 but modal box show me 2:32 and copies 2:32. 

If I reload page, I can copy 2:37.

![image](https://user-images.githubusercontent.com/241385/141711917-e541aaf3-0158-409b-9bda-cc3d2fc0a45b.png)

**Comment by osamasayed** [comment]
Alsalmu Alikum @selim Jazak Allah Kahiran for reporting the issue. It seems the issue is related to the current [live](https://quran.com) website (quran.com) whose code is inside [v2's repo](https://github.com/quran/quran.com-frontend-v2). In the [Next.js's version](http://beta.quran.com/) we don't seem to have this issue anymore Alhamdulelah.
<img width="954" alt="Screen Shot 2021-11-15 at 15 36 01" src="https://user-images.githubusercontent.com/15169499/141749736-ab2953e3-eaa0-4d59-be5b-07071110a873.png">

**Comment by selim** [comment]
Please fix the url in "For example this url has list of bugs, things we need help with, and upcoming features." at page-> https://beta.quran.com/developers
