### ISSUE TITLE
"Select language" does not have enough width

### ISSUE THREAD

**Issue by muhajirdev** [quran/quran.com-frontend-next#798]
![image](https://user-images.githubusercontent.com/12745166/142731882-31dcbc19-a319-4456-94ab-f59c41344081.png)

- This should show "Indonesia" instead of "Indone"

**Comment by iyunusov** [comment]
I am working on this.
Question arises with this issue and there're two simple ways I know for fixing it:
1. By setting max-width & min-width (following this again if there's some super long option name, it won't still appear fully, since we'll be still limiting the width at some point).
2. By calculated the box width depending on the option length and then inlining the css.

The first option seems to be more cleaner to me, since languages usually aren't very long (say not more than 20 letters)...

**Comment by muhajirdev** [comment]
I don't have a strong opinion. option 1 looks good 👍

**Comment by circlePulse** [comment]
Shouldn't this be closed?

**Comment by iyunusov** [comment]
> Shouldn't this be closed?

PR still has questions.
